colors:
    fieldStrokeColor: [228,99,37]
    fieldBgColor: [235,238,248]
    formBgColor: [245,245,245]

labelFsize: 9
inputFsize: 8
insideLeftPadding: 7
insideTopPadding: 4
yAfterTitle: 3
yAfterPart: 5
yAfterPartTitle: 3
